// AUTO-GENERATED by scripts/process-galleries.mjs — do not edit by hand.
export interface GalleryImage { src: string; w: number; h: number; }
export interface GridCard { slug: string; names: string; location: string; thumb: string; }
export interface Gallery { names: string; location: string; images: GalleryImage[]; }

export const GRID_CARDS: GridCard[] = [
  {
    "slug": "francesca-roberto",
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "thumb": "/images/portfolio/francesca-roberto/t1.webp"
  },
  {
    "slug": "elena-davide",
    "names": "Elena & Davide",
    "location": "Val d'Orcia, Italia",
    "thumb": "/images/portfolio/elena-davide/t1.webp"
  },
  {
    "slug": "sofia-alessandro-positano",
    "names": "Sofia & Alessandro",
    "location": "Positano, Italia",
    "thumb": "/images/portfolio/sofia-alessandro-positano/t1.webp"
  },
  {
    "slug": "emma-luca",
    "names": "Emma & Luca",
    "location": "Siena, Italia",
    "thumb": "/images/portfolio/emma-luca/t1.webp"
  },
  {
    "slug": "valentina-matteo",
    "names": "Valentina & Matteo",
    "location": "Ravello, Italia",
    "thumb": "/images/portfolio/valentina-matteo/t1.webp"
  },
  {
    "slug": "martina-federico",
    "names": "Martina & Federico",
    "location": "San Gimignano, Italia",
    "thumb": "/images/portfolio/martina-federico/t1.webp"
  },
  {
    "slug": "chiara-marco",
    "names": "Chiara & Marco",
    "location": "Firenze, Italia",
    "thumb": "/images/portfolio/chiara-marco/t1.webp"
  },
  {
    "slug": "sofia-alessandro",
    "names": "Sofia & Alessandro",
    "location": "Lago di Como, Italia",
    "thumb": "/images/portfolio/sofia-alessandro/t1.webp"
  },
  {
    "slug": "francesca-roberto",
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "thumb": "/images/portfolio/francesca-roberto/t2.webp"
  },
  {
    "slug": "elena-davide",
    "names": "Elena & Davide",
    "location": "Val d'Orcia, Italia",
    "thumb": "/images/portfolio/elena-davide/t2.webp"
  },
  {
    "slug": "sofia-alessandro-positano",
    "names": "Sofia & Alessandro",
    "location": "Positano, Italia",
    "thumb": "/images/portfolio/sofia-alessandro-positano/t2.webp"
  },
  {
    "slug": "emma-luca",
    "names": "Emma & Luca",
    "location": "Siena, Italia",
    "thumb": "/images/portfolio/emma-luca/t2.webp"
  },
  {
    "slug": "valentina-matteo",
    "names": "Valentina & Matteo",
    "location": "Ravello, Italia",
    "thumb": "/images/portfolio/valentina-matteo/t2.webp"
  },
  {
    "slug": "martina-federico",
    "names": "Martina & Federico",
    "location": "San Gimignano, Italia",
    "thumb": "/images/portfolio/martina-federico/t2.webp"
  },
  {
    "slug": "chiara-marco",
    "names": "Chiara & Marco",
    "location": "Firenze, Italia",
    "thumb": "/images/portfolio/chiara-marco/t2.webp"
  },
  {
    "slug": "sofia-alessandro",
    "names": "Sofia & Alessandro",
    "location": "Lago di Como, Italia",
    "thumb": "/images/portfolio/sofia-alessandro/t2.webp"
  },
  {
    "slug": "francesca-roberto",
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "thumb": "/images/portfolio/francesca-roberto/t3.webp"
  },
  {
    "slug": "elena-davide",
    "names": "Elena & Davide",
    "location": "Val d'Orcia, Italia",
    "thumb": "/images/portfolio/elena-davide/t3.webp"
  },
  {
    "slug": "sofia-alessandro-positano",
    "names": "Sofia & Alessandro",
    "location": "Positano, Italia",
    "thumb": "/images/portfolio/sofia-alessandro-positano/t3.webp"
  },
  {
    "slug": "emma-luca",
    "names": "Emma & Luca",
    "location": "Siena, Italia",
    "thumb": "/images/portfolio/emma-luca/t3.webp"
  },
  {
    "slug": "valentina-matteo",
    "names": "Valentina & Matteo",
    "location": "Ravello, Italia",
    "thumb": "/images/portfolio/valentina-matteo/t3.webp"
  },
  {
    "slug": "martina-federico",
    "names": "Martina & Federico",
    "location": "San Gimignano, Italia",
    "thumb": "/images/portfolio/martina-federico/t3.webp"
  },
  {
    "slug": "chiara-marco",
    "names": "Chiara & Marco",
    "location": "Firenze, Italia",
    "thumb": "/images/portfolio/chiara-marco/t3.webp"
  },
  {
    "slug": "sofia-alessandro",
    "names": "Sofia & Alessandro",
    "location": "Lago di Como, Italia",
    "thumb": "/images/portfolio/sofia-alessandro/t3.webp"
  },
  {
    "slug": "francesca-roberto",
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "thumb": "/images/portfolio/francesca-roberto/t4.webp"
  },
  {
    "slug": "elena-davide",
    "names": "Elena & Davide",
    "location": "Val d'Orcia, Italia",
    "thumb": "/images/portfolio/elena-davide/t4.webp"
  },
  {
    "slug": "chiara-marco",
    "names": "Chiara & Marco",
    "location": "Firenze, Italia",
    "thumb": "/images/portfolio/chiara-marco/t4.webp"
  },
  {
    "slug": "sofia-alessandro",
    "names": "Sofia & Alessandro",
    "location": "Lago di Como, Italia",
    "thumb": "/images/portfolio/sofia-alessandro/t4.webp"
  },
  {
    "slug": "francesca-roberto",
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "thumb": "/images/portfolio/francesca-roberto/t5.webp"
  }
];

export const GALLERIES: Record<string, Gallery> = {
  "francesca-roberto": {
    "names": "Francesca & Roberto",
    "location": "Capri, Italia",
    "images": [
      {
        "src": "/images/portfolio/francesca-roberto/g1.webp",
        "w": 1600,
        "h": 988
      },
      {
        "src": "/images/portfolio/francesca-roberto/g2.webp",
        "w": 1189,
        "h": 818
      },
      {
        "src": "/images/portfolio/francesca-roberto/g3.webp",
        "w": 1189,
        "h": 818
      },
      {
        "src": "/images/portfolio/francesca-roberto/g4.webp",
        "w": 1189,
        "h": 818
      },
      {
        "src": "/images/portfolio/francesca-roberto/g5.webp",
        "w": 1189,
        "h": 818
      }
    ]
  },
  "elena-davide": {
    "names": "Elena & Davide",
    "location": "Val d'Orcia, Italia",
    "images": [
      {
        "src": "/images/portfolio/elena-davide/g1.webp",
        "w": 1104,
        "h": 1600
      },
      {
        "src": "/images/portfolio/elena-davide/g2.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/elena-davide/g3.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/elena-davide/g4.webp",
        "w": 1408,
        "h": 714
      }
    ]
  },
  "sofia-alessandro-positano": {
    "names": "Sofia & Alessandro",
    "location": "Positano, Italia",
    "images": [
      {
        "src": "/images/portfolio/sofia-alessandro-positano/g1.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/sofia-alessandro-positano/g2.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/sofia-alessandro-positano/g3.webp",
        "w": 1408,
        "h": 714
      }
    ]
  },
  "emma-luca": {
    "names": "Emma & Luca",
    "location": "Siena, Italia",
    "images": [
      {
        "src": "/images/portfolio/emma-luca/g1.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/emma-luca/g2.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/emma-luca/g3.webp",
        "w": 1408,
        "h": 714
      }
    ]
  },
  "valentina-matteo": {
    "names": "Valentina & Matteo",
    "location": "Ravello, Italia",
    "images": [
      {
        "src": "/images/portfolio/valentina-matteo/g1.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/valentina-matteo/g2.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/valentina-matteo/g3.webp",
        "w": 1408,
        "h": 714
      }
    ]
  },
  "martina-federico": {
    "names": "Martina & Federico",
    "location": "San Gimignano, Italia",
    "images": [
      {
        "src": "/images/portfolio/martina-federico/g1.webp",
        "w": 1600,
        "h": 811
      },
      {
        "src": "/images/portfolio/martina-federico/g2.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/martina-federico/g3.webp",
        "w": 1600,
        "h": 811
      }
    ]
  },
  "chiara-marco": {
    "names": "Chiara & Marco",
    "location": "Firenze, Italia",
    "images": [
      {
        "src": "/images/portfolio/chiara-marco/g1.webp",
        "w": 1600,
        "h": 967
      },
      {
        "src": "/images/portfolio/chiara-marco/g2.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/chiara-marco/g3.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/chiara-marco/g4.webp",
        "w": 1408,
        "h": 714
      }
    ]
  },
  "sofia-alessandro": {
    "names": "Sofia & Alessandro",
    "location": "Lago di Como, Italia",
    "images": [
      {
        "src": "/images/portfolio/sofia-alessandro/g1.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/sofia-alessandro/g2.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/sofia-alessandro/g3.webp",
        "w": 1408,
        "h": 714
      },
      {
        "src": "/images/portfolio/sofia-alessandro/g4.webp",
        "w": 1408,
        "h": 714
      }
    ]
  }
};
